version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: myPassWord123
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: